name: librotech
description: "LibroTech es una aplicación móvil innovadora diseñada para mejorar
  la experiencia de los entusiastas de los libros de tecnología."

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  card_loading: ^0.3.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: 5.8.0
  flutter_rating_bar: ^4.0.1
  get: ^4.7.2
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mocktail: ^1.0.4

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env.development
